name: foundation
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1 # [Target] Modern Standard (SDXL, Flux, AnimateDiff)
  - xformers